### ISSUE TITLE
TypeError: 'ChatPermissions' object does not support item assignment

### ISSUE THREAD

**Issue by vlab97** [xvitaly/ecasbot#205]
### Problem details

2023-02-09 14:04:50,962:ERROR:Не могу ограничить в правах нового пользователя ID в чате -ID () из-за отсутствия прав администратора.
Traceback (most recent call last):
  File "ecasbot\__init__.py", line 767, in __handle_join
  File "telebot\__init__.py", line 3001, in restrict_chat_member
  File "telebot\apihelper.py", line 977, in restrict_chat_member
TypeError: 'ChatPermissions' object does not support item assignment

Сведения об установленных пакетах:
pip list
Package                   Version
------------------------- ---------
altgraph                  0.17.3
certifi                   2022.12.7
charset-normalizer        2.0.12
emoji                     2.2.0
future                    0.18.3
idna                      3.4
pefile                    2022.5.30
pip                       23.0
pyinstaller               5.7.0
pyinstaller-hooks-contrib 2022.15
pywin32-ctypes            0.2.0
requests                  2.28.0
setuptools                65.5.0
urllib3                   1.26.14

### Steps to reproduce

1 Вход в чат нового участника
2 Попытка ограничения ботом нового участника

### Expected behavior

1 Вход в чат нового участника
2 Наложение ограничения на нового участника

### Actual behavior

Ограничение не накладывается и выходит ошибка.

### Project version

1.8

### Platform

Microsoft Windows

### OS version

Windows 11

### Python version

3.11

### Installation type

Other

### Logs

```text
2023-02-09 13:51:02,347:INFO:Новый пользователь Игорь (ID) вступил в чат -1001773242572 (). Баллы: 50.
2023-02-09 13:51:02,602:ERROR:Не могу ограничить в правах нового пользователя ID в чате -ID () из-за отсутствия прав администратора.
Traceback (most recent call last):
  File "ecasbot\__init__.py", line 767, in __handle_join
  File "telebot\__init__.py", line 3001, in restrict_chat_member
  File "telebot\apihelper.py", line 977, in restrict_chat_member
TypeError: 'ChatPermissions' object does not support item assignment
2023-02-09 13:57:18,472:INFO:Новый пользователь Игорь (ID) вступил в чат -1001773242572 (). Баллы: 50.
2023-02-09 13:57:18,719:ERROR:Не могу ограничить в правах нового пользователя ID в чате -ID () из-за отсутствия прав администратора.
Traceback (most recent call last):
  File "ecasbot\__init__.py", line 762, in __handle_join
  File "telebot\__init__.py", line 3001, in restrict_chat_member
  File "telebot\apihelper.py", line 977, in restrict_chat_member
TypeError: 'ChatPermissions' object does not support item assignment
```

**Comment by vlab97** [comment]
Инсталлятор с релиза такую же ошибку дает.

**Comment by xvitaly** [comment]
Спасибо за сообщение об ошибке.

Баг внутри библиотеки pyTelegramBotAPI. Если задан параметр `use_independent_chat_permissions`, он пытается изменить неизменяемый объект, что заканчивается ошибкой. Я отправил баг-репорт в pyTelegramBotAPI, но в качестве временной меры можно просто убрать параметр `use_independent_chat_permissions=True` из всех вызовов `restrict_chat_member`.

**Comment by vlab97** [comment]
Спасибо. Убрал данный параметр. Посмотрим дальше

**Comment by xvitaly** [comment]
> Спасибо. Убрал данный параметр. Посмотрим дальше

Сейчас будет более правильный фикс.

**Comment by xvitaly** [comment]
@vlab97 Просьба проверить. Теперь должно работать.

**Comment by vlab97** [comment]
> @vlab97 Просьба проверить. Теперь должно работать.

Пока ограничился только удалением параметра. Сегодня-завтра внесу правки согласно последнему комменту

**Comment by vlab97** [comment]
pyTelegramBotAPI выкатили исправление. Есть смысл проверять его с возвратом удалённого параметра?

**Comment by xvitaly** [comment]
> pyTelegramBotAPI выкатили исправление. Есть смысл проверять его с возвратом удалённого параметра?

Да, сейчас дождёмся релиза и можно откатить мой коммит.

**Comment by xvitaly** [comment]
Релиз исправленной версии pyTelegramBotAPI спустя сутки так и не состоялся, поэтому решил выпустить релиз [1.8.1](https://github.com/xvitaly/ecasbot/releases/tag/v1.8.1) с удалённым параметром `use_independent_chat_permissions=True`.
